### PR TITLE
Stop relying on IntelliJ internals

### PR DESCRIPTION
**Pull request by reda-alaoui**
As of today, it looks like there is no more need to "hack" `CodeStyleManager`.

With this change, the plugin does not override `CodeStyleManager` anymore neither relies on `ComponentManagerImpl` IntelliJ internal class. Instead, the plugin extends the `FormatterService` interface which is the official `Jetbrains` way of providing formatting features.

`FormatterService` opens up the ability to provide an `ImportOptimizer`. If this change gets merged, I will open another PR to add import reordering for #94 (commit ready at https://github.com/Cosium/google-java-format/commit/c11ef75d202f9ddbbc38bb6df63454acf2ba78e8 ).

I thought I found an issue explained at https://github.com/google/google-java-format/pull/820#issuecomment-1221522672 . But in the end, I think it was a false positive.

The current change is expected to retain the old behaviour without any "hack".

### CODE REVIEW

**Comment by reda-alaoui** [comment]
Ping :)

**Comment by reda-alaoui** [comment]
Ping :)

**Comment by bogdandrutu** [comment]
Ping :)

**Comment by bogdandrutu** [comment]
@cushon can you please review/merge this before next release

**Comment by bogdandrutu** [comment]
@cushon 🙏

**Comment by cushon** [comment]
Sorry for the lack of response on this PR -- @plumpy has been working on some similar changes in parallel that should be available soon

**Comment by bogdandrutu** [comment]
@cushon as long as I don't have to install the coding style (for imports, etc.) in Intelijj I am good. Thanks for taking care of this. Please also do a release after the code is available.

**Comment by cushon** [comment]
> Sorry for the lack of response on this PR -- @plumpy has been working on some similar changes in parallel that should be available soon

This happened in https://github.com/google/google-java-format/commit/84b2c9a2ba382ee7a968518b46afb0d6000ada8d, and a new version of the IntelliJ plugin has been released

**Pull request closed without merging**
