### PR TITLE
Expand hard-coded list of type qualifiers

### PR DESCRIPTION
**Pull request by mernst**
This change is necessary even if a `-Dtypeannotationconfig=_filename_` flag is implemented as mentioned in https://github.com/google/google-java-format/issues/5.  (That filename would be for recently-created annotations, or ones that are private to a project or a company.)

### CODE REVIEW

**Comment by mernst** [comment]
The CI failure is the same as is currently occurring on the master branch.

**Comment by cushon** [comment]
> This change is necessary even if a -Dtypeannotationconfig=_filename_ flag is implemented as mentioned in https://github.com/google/google-java-format/issues/5

I think I see what you mean, but that isn't the way I was thinking about it. With `-Dtypeannotationconfig=` people could create their own lists, and we wouldn't have to try to maintain an exhaustive list of type use annotations in public libraries.

**Comment by mernst** [comment]
> > This change is necessary even if a -Dtypeannotationconfig=_filename_ flag is implemented as mentioned in #5
> 
> I think I see what you mean, but that isn't the way I was thinking about it. With `-Dtypeannotationconfig=` people could create their own lists, and we wouldn't have to try to maintain an exhaustive list of type use annotations in public libraries.

Thanks for clarifying how you were thinking about it; that was not clear to me before.  My view is (as stated in the PR description) that the extra filename would be rarely used:  for recently-created annotations or for ones that are private to a project or a company.

If we apply your view consistently, then GJF should not support `org.jspecify.nullness.Nullable`.  Every user who wishes to use that annotation should create a side file containing its name and configure GJF to use that file.  I think this is unreasonable; do you agree?

There is no need to maintain an *exhaustive* list -- no one (other than you?) has suggested that.  But maintaining a *useful* list would be helpful to users.  It would significantly reduce user effort, and it would reduce inadvertent formatting differences among users and among projects.

Another argument in favor of this pull request is that it is consistent with how the current GJF implementation works.

**Comment by cushon** [comment]
This is not the approach I want to take at this time. I would take a PR for the approach described in https://github.com/google/google-java-format/issues/5#issuecomment-1183638329

**Comment by mernst** [comment]
I would be curious to understand the reasoning.  I noted some tradeoffs that favor this pull request, but you didn't have any criticism of it, nor mention anything that recommends the approach of every user having to create a side file and customize their buildfile.

**Pull request closed without merging**
