### PR TITLE
Add scripts to build native binary (using a container)

### LINKED ISSUE #868: Release native builds
Hello

GraalVM native-image support appears to have been added a little while ago https://github.com/google/google-java-format/pull/728 (see also https://github.com/google/google-java-format/issues/358). However there are no official native build release on the release page https://github.com/google/google-java-format/releases. is it working ?

Providing these could greatly benefit to java tooling as it would allow fast formatting without having to rely on IDEs customization and while being fully compliant with google style guide. This could be easily imported in Visual Studio Code for example.

Platform targets of most interest would be win32-x64, linux-x64, darwin-x64, darwin-arm64.

### LINKED ISSUE #894: Can't build native image with GraalVM 22.3.0 Java 17 CE
A native image built via `mvn -Pnative -DskipTests package` with GraalVM 22.3.0 Java 17 CE fails at runtime with:

```
MyClass.java: error: com.sun.tools.javac.parser.Tokens$TokenKind
java.lang.NoClassDefFoundError: com.sun.tools.javac.parser.Tokens$TokenKind
	at com.google.googlejavaformat.java.JavaInput.buildToks(JavaInput.java:350)
	at com.google.googlejavaformat.java.JavaInput.buildToks(JavaInput.java:335)
	at com.google.googlejavaformat.java.JavaInput.<init>(JavaInput.java:277)
	at com.google.googlejavaformat.java.Formatter.getFormatReplacements(Formatter.java:260)
	at com.google.googlejavaformat.java.Formatter.formatSource(Formatter.java:247)
	at com.google.googlejavaformat.java.FormatFileCallable.call(FormatFileCallable.java:45)
	at com.google.googlejavaformat.java.FormatFileCallable.call(FormatFileCallable.java:26)
	at java.base@17.0.5/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
```

While this seems to be fixed by adding `-J--add-exports=...` `buildArgs` to the `native-maven-plugin` config, the produced native image still fails at runtime with a different error:

```
MyClass.java: error: com.google.googlejavaformat.java.java17.Java17InputAstVisitor. This exception was synthesized during native image building from a call to java.lang.Class.forName(String) with constant arguments.
java.lang.LinkageError: com.google.googlejavaformat.java.java17.Java17InputAstVisitor. This exception was synthesized during native image building from a call to java.lang.Class.forName(String) with constant arguments.
	at com.google.googlejavaformat.java.Formatter.format(Formatter.java:162)
	at com.google.googlejavaformat.java.Formatter.getFormatReplacements(Formatter.java:271)
	at com.google.googlejavaformat.java.Formatter.formatSource(Formatter.java:247)
	at com.google.googlejavaformat.java.FormatFileCallable.call(FormatFileCallable.java:45)
	at com.google.googlejavaformat.java.FormatFileCallable.call(FormatFileCallable.java:26)
	at java.base@17.0.5/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
Caused by: java.lang.ClassNotFoundException: com.google.googlejavaformat.java.java17.Java17InputAstVisitor. This exception was synthesized during native image building from a call to java.lang.Class.forName(String) with constant arguments.
	at com.google.googlejavaformat.java.Formatter.format(Formatter.java:157)
	... 10 more
```

I haven't found a fix for this yet.

### PR DESCRIPTION
**Pull request by vorburger**
Fixes #894 and fixes #868!

~~As is, this doesn't work yet, launching `./build-natives.sh` fails with:~~

~~[ERROR] Failed to execute goal org.graalvm.buildtools:native-maven-plugin:0.9.13:build (build-native) on project google-java-format: 'gu' tool wasn't found. This probably means that JDK at isn't a GraalVM distribution. -> [Help 1]~~

~~What this `gu` tool which apparently comes with a GraalVM distribution, but isn't included in a Graal container base image?!~~

~~@fmeum @cushon perhaps you would know and like to chime in here?~~

PS: This includes #1044, so don't "squash merge" this PR, but merge that one (1044) first, then "rebase merge" this one, and only the 2nd commit would be merged, and 1st one dropped. (Or I could rebase this after that is merged, so this is cleaner, if requested.)

### CODE REVIEW

**Comment by vorburger** [comment]
> What this gu tool which apparently comes with a GraalVM distribution, but isn't included in a Graal container base image?!

According to https://github.com/oracle/graal/issues/1868, `gu` is no longer available / needed?

Perhaps bumping the version of `org.graalvm.buildtools:native-maven-plugin` helps? I'll try...

**Comment by vorburger** [comment]
Hah! It now "works" - kind of. How cool is this?

To make this fully ready for review as-is, from my side, I would need to do some more work to change the script to not use volumes in `docker build`, which works for locally, for me, on Fedora, with Podman; but with Docker, on Debian in a GitHub action, apparently `docker build` cannot use volumes?! How dumb is that... But it should be possible to rewrite it differently, probably in the end using both `docker build` and `docker run`. (Or with multi stage images, e.g. as explained [here](https://vsupalov.com/cache-docker-build-dependencies-without-volume-mounting/) or [here](https://stackoverflow.com/questions/26050899/how-to-mount-host-volumes-into-docker-containers-in-dockerfile-during-build); although that wouldn't really work for the cache I'm using.)

Before spending a bit more time to do that ^^^ I would love a signal from reviewers / project committers if this would be merged, when green?

@cushon @cpovirk

**Comment by cushon** [comment]
Thanks for investigating this!

Is https://github.com/graalvm/setup-graalvm a potential alternative to using docker to set up GraalVM?

**Comment by vorburger** [comment]
> Is https://github.com/graalvm/setup-graalvm a potential alternative to using docker to set up GraalVM?

It might - I hadn't seen (searched for) that approach.

Why I personally prefer this route over a GitHub Actions based approach is that this make it very easy to use locally:

Anyone who has Docker, even e.g. on a Mac or Windows, can launch `./build-natives.sh` - and, voilà, natives magically come out! Without needing to worry about having anything else installed. (The Mac or Windows cross compilation is orthogonal, of course.)

With GitHub Actions, it's "only possible on (and "locked into") GitHub", which... I personally don't like much.

What do you think?

**Comment by cushon** [comment]
Thanks for the background. I think my preference here as a maintainer is to try to use the dependencies and process we already have, vs. replacing it with a new one. GitHub Actions isn't perfect, but one concrete benefit here is that it would provide a way to support mac binaries.

**Comment by vorburger** [comment]
OK, makes sense; then I'll try that approach! Some other day though, and I'll raise a separate new PR.

**Pull request closed without merging**
