### PR TITLE
Upgrade to JUnit 5 and Surefire 2.19.1

### PR DESCRIPTION
**Pull request by sormuras**
This PR introduces **JUnit 5** as a dependency and ports a single test class, namely `NewlinesTest.java`, to the new [JUnit Jupiter API](http://junit.org/junit5/docs/current/user-guide/).

### Todo
- [ ] Convert all remaining test classes to JUnit 5

### CODE REVIEW

**Comment by cushon** [comment]
This will have to wait until we start using JUnit 5 internally, which could take a while.

**Comment by sormuras** [comment]
Alright. Will keep the version(s) up-to-date and convert the rest of the tests when you're readsy to switch.

**Comment by cushon** [comment]
Unfortunately I don't have an ETA, we're going to be using JUnit 4 for the foreseeable future. I'm going to close this rather than leave it open indefinitely, but I'm happy to revisit if/when we make the switch.

**Comment by sormuras** [comment]
No problem.

**Pull request closed without merging**
