### PR TITLE
Preserve tabular arguments for mixed sign numeric lists.

### LINKED ISSUE #400: Formatting of tabular array initializer confused by negative numbers
Negative numbers in the initializer of an array with tabular formatting makes google-java-format not preserve the layout.

```
$ cat T.java
package foo;

public class FormattingTester {

  private static final double[] flinePoints = {
    95.0, 75.0, 95.0, 75.0,
    95.0, 75.0, 95.0, 75.0
  };

  private static final double[] flinePoints2 = {
    95.0, 75.0, -95.0, 75.0,
    -95.0, 75.0, 95.0, 75.0
  };
}

$ java -jar ~/Downloads/google-java-format-1.7-all-deps.jar T.java
package foo;

public class FormattingTester {

  private static final double[] flinePoints = {
    95.0, 75.0, 95.0, 75.0,
    95.0, 75.0, 95.0, 75.0
  };

  private static final double[] flinePoints2 = {95.0, 75.0, -95.0, 75.0, -95.0, 75.0, 95.0, 75.0};
}

```

### PR DESCRIPTION
**Pull request by andrewkreid**
Treats unary minus literals (eg -4.0) as their underlying type when checking if all elements in a tabular list are of the same Tree.Kind.

Resolves #400

### CODE REVIEW

**Comment by ronshapiro** [comment]
What about other unary expressions?

```java
-1, -2,
+1, +2,

++x, y++,
--q, v++,
```

**Comment by andrewkreid** [comment]
Good point. I'll update when I get time in a coupla days.

**Comment by andrewkreid** [comment]
Updated to work on all types of UnaryTree.

**Comment by andrewkreid** [comment]
Friendly ping.

**Pull request closed without merging**
