### PR TITLE
Remove redundant type arguments and apply google-java-format

### PR DESCRIPTION
**Pull request by jbduncan**

### CODE REVIEW

**Comment by jbduncan** [comment]
I do realise that this PR is 1. rather large and 2. that it came out of the blue, so I'd be happy to discuss the merits of it with someone from the google-java-format team, and even to break it down into smaller PRs if desired.

**Comment by jbduncan** [comment]
*ping*

**Comment by jbduncan** [comment]
PR branch is now rebased on google/google-java-format/master.

**Comment by jbduncan** [comment]
@cushon, I wonder if it would it be possible to start discussing this PR soon?

**Comment by cushon** [comment]
It's not clear to me this is a readability improvement. The type argument can help document empty collections, e.g. `Optional.<ExpressionTree>absent(), Optional.<TypeWithDims>absent()` vs. `Optional.absent(), Optional.absent()`.

**Comment by jbduncan** [comment]
> It's not clear to me this is a readability improvement. The type argument can help document empty collections, e.g. Optional.<ExpressionTree>absent(), Optional.<TypeWithDims>absent() vs. Optional.absent(), Optional.absent().

@cushon Ah yes, okay. I see what you mean.

Do you have any thoughts about the other changes I've made in this PR?

E.g.
`Iterators.<ExpressionTree>peekingIterator(arguments.iterator());`
-->
`Iterators.peekingIterator(arguments.iterator());`?

I'd totally understand if you'd rather that I just close this PR at this point. :)

**Comment by cushon** [comment]
I think most of it looks good, but I may pick-and-choose a bit when I merge it.

For some of the `ImmutableList.of()` cases it might be better to use `/* parameterName= */` comments than type arguments.

**Comment by jbduncan** [comment]
LGTM @cushon. Thank you very much for merging in and adjusting my PR as was needed. :)

**Pull request closed without merging**
