### PR TITLE
Add support for custom google-java-format jar

### LINKED ISSUE #44: google-java-format-diff.py is unusable without rolling your own wrapper script
google-java-format-diff.py assumes there is an executable in $PATH named "google-java-format", which is not part of any published releases. The basic instructions say to run with "java -jar", so to make this work, someone has to write a wrapper script. I am capable of rolling my own but it really seems like this should be part of the distribution.

### PR DESCRIPTION
**Pull request by simon0191**
Adds --google-java-format-jar option that lets the user specify a path to the google-java-format-jar.

Close #44

### CODE REVIEW

**Comment by simon0191** [comment]
I signed it!

**Comment by medb** [comment]
Close #108

**Comment by dhalperi** [comment]
(Driveby FYI - scanning the repo.)

@ronshapiro the commit message on fa113c6 of `Fixes #44, #227` unfortunately only closes the first one. Needs to be `Fixes #44, Fixes #227` to auto-close this.

(This should probably be closed now)?

**Comment by eaftan** [comment]
Thanks @dhalperi.  Closing this one as fixed by fa113c6.

**Pull request closed without merging**
