### PR TITLE
Add support for 2019.x IDEs.

### PR DESCRIPTION
**Pull request by medb**

### CODE REVIEW

**Comment by sormuras** [comment]
Could this update be merged ... soon?

TIA

**Comment by Askent** [comment]
I've tried to build-install manually from this PR, got an exception
```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'value' of com/intellij/openapi/util/UserDataHolderBase.putUserDataIfAbsent must not be null
	at com.intellij.openapi.util.UserDataHolderBase.$$$reportNull$$$0(UserDataHolderBase.java)
	at com.intellij.openapi.util.UserDataHolderBase.putUserDataIfAbsent(UserDataHolderBase.java)
	at com.intellij.openapi.util.NotNullLazyKey.getValue(NotNullLazyKey.java:42)
	at com.intellij.psi.util.CachedValuesManager.getManager(CachedValuesManager.java:43)
	at com.intellij.internal.statistic.utils.StatisticsUtilKt.getSafeToReportPluginIds(StatisticsUtil.kt:179)
	at com.intellij.internal.statistic.utils.StatisticsUtilKt.isSafeToReport(StatisticsUtil.kt:250)
	at com.intellij.diagnostic.DefaultIdeaErrorLogger.canHandle(DefaultIdeaErrorLogger.java:63)
	at com.intellij.diagnostic.DialogAppender.appendToLoggers(DialogAppender.java:90)
	at com.intellij.diagnostic.DialogAppender.lambda$queueAppend$0(DialogAppender.java:63)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:699)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:648)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:343)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Finally I've hacked `idea_plugin/build.gradle` with next code:
```
plugins {
  id "org.jetbrains.intellij" version "0.4.2"
}

repositories {
  mavenCentral()
  maven { url 'http://dl.bintray.com/jetbrains/intellij-plugin-service' }
}

ext {
  googleJavaFormatVersion = '1.7'
}

apply plugin: 'java'

sourceCompatibility = JavaVersion.VERSION_1_8
targetCompatibility = JavaVersion.VERSION_1_8

intellij {
  pluginName = "google-java-format"
  updateSinceUntilBuild = true
  version '191-EAP-SNAPSHOT'

  patchPluginXml {
    pluginDescription = "Formats source code using the google-java-format tool. This version of " +
                        "the plugin uses version ${googleJavaFormatVersion} of the tool."
    version = "${googleJavaFormatVersion}.0.0"
  }

  publishPlugin {
    username = project.ext.properties.jetbrainsPluginRepoUsername
    password = project.ext.properties.jetbrainsPluginRepoPassword
  }
}
```
Built and ran successfully on IDEA-U-2019-4738.6 JRE 8b152_1402

**Comment by medb** [comment]
@google/shaka-player  I think that without `untilBuild` you will need to recompile plugin for each new IDE version, which is less than optimal. May you try to add back `untilBuild = 199` field to your patch and see if it still works for you?

**Comment by medb** [comment]
@Askent I just updated PR to upgrade Gradle Intellij plugin, may you give it a try as well?

**Comment by Askent** [comment]
@medb yep, it works with since/until you provided. The only one thing I have to specify is:
```
sourceCompatibility = JavaVersion.VERSION_1_8
targetCompatibility = JavaVersion.VERSION_1_8
```
My gradle using 9 & 11 jdk version fails, with conflicts on other plugins & above specified exception. 
I can commit this change to this PR if you don't mind.

**Comment by Richard-Mathie** [comment]
How exactly do i build this plugin for idea? I can run `mvn install` but this just makes the core target jars. what do i need to do to make the plugin.zip for installation from disk by intellij?

**Comment by plumpy** [comment]
cd into the idea_plugin directory and run `gradle build`. The plugin will be in build/distributions/idea_plugin.zip.

**Comment by plumpy** [comment]
I uploaded a version that supports 2019.1 now (1.7.0.1). The commit for this version will be in GitHub soon.

**Comment by sormuras** [comment]
Yehaa! 👍

**Pull request closed without merging**
