### PR TITLE
'jfmt' tool for the fast formating

### PR DESCRIPTION
**Pull request by pvlbzn**
I wrote a tool, Python script, which is able to format .java files in directory and subdirectories or just a single .java file. I use it like `$ jfmt /path/to/project/dir` and I find it very convenient way to format my code as a whole.

Script was tested on Linux and Mac.

I hope this tool can be useful for others. Also, I not quite sure about the name. I was inspired by `fmt` from the Go lang.

### CODE REVIEW

**Comment by kevinb9n** [comment]
Thanks for thinking about how to make this project better!

Question: If `google-java-format` could take directories as arguments and
process them recursively, would a separate wrapper be necessary?


On Tue, May 24, 2016 at 5:37 AM, Pavel Bazin <notifications@github.com>
wrote:

> I wrote a tool, Python script, which is able to format .java files in
> directory and subdirectories or just a single .java file. I use it like $
> jfmt /path/to/project/dir and I find it very convenient way to format my
> code as a whole.
>
> Script was tested on Linux and Mac.
>
> I hope this tool can be useful for others. Also, I not quite sure about
> the name. I was inspired by fmt from the Go lang.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/google/google-java-format/pull/50
> Commit Summary
>
>    - Python script 'jfmt' for formatting automatization.
>    - Fixed comment in jfmt.
>    - Added 'Purpose' description to 'jfmt'.
>
> File Changes
>
>    - *A* scripts/jfmt.py
>    <https://github.com/google/google-java-format/pull/50/files#diff-0>
>    (103)
>
> Patch Links:
>
>    - https://github.com/google/google-java-format/pull/50.patch
>    - https://github.com/google/google-java-format/pull/50.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/google/google-java-format/pull/50>
>



-- 
Kevin Bourrillion | Java Librarian | Google, Inc. | kevinb@google.com

**Comment by sherter** [comment]
>Question: If `google-java-format` could take directories as arguments and
process them recursively, would a separate wrapper be necessary?

I had this idea before, but as you suggest to put more functionality into the executable I think it should be considered now: What do you think about separating library code and executable into two artifacts? This would prevent problems like https://github.com/google/google-java-format/issues/42 in the future and tools like dagger could depend only on the library. CLI parsing libraries used in the executable are transitively resolved right now, whether you use google-java-format as standalone tool or only the `Formatter`.

**Comment by pvlbzn** [comment]
If you ask me, I'll write this kind of a tool in both proposed cases.

If `google-java-format` will be able to traverse over a tree I'll call its "native method" from the script instead of applying it, google-java-format, to the each file. Because it is a more convenient way to use it as a separate tool.

Consider following use case:
```
$ git clone some/java/project.git
$ jfmt
```
Now you are able to read formatted code like it was formatted from the beginning. 

Or
```
$ jfmt
$ git commit -am "comment"
```
To write code in comfortable style and format it afterwards to common style. I can't say that last example can be considered as a good one, but it shows the point.

Cheers.

**Comment by cushon** [comment]
Thanks for the patch! I'm not sure it's worth adding a separate wrapper for this, though. Does `google-java-format -i $(find . -type f -name "*.java")` do what you need?

@sherter good idea, I filed #54 to separate the CLI into its own artifact.

**Comment by pvlbzn** [comment]
Thanks for answer @cushon !

This script is aimed on an integration into users shell. The key point is to type 4 characters and format whole project at once, or type 5 characters and drag-n-drop particular `.java` file into the shell to format it. IDE environments usually have a built-in terminal feature, so it can used out of one programming env.

However, perhaps it will be too much to have two wrappers. I proposed this tool because it serves well to me, with an unix-like idea "one tool for a one job". May be it is a good idea to add this functionality into the existing script? Otherwise lets close this request.

Cheers!

**Pull request closed without merging**
